### ISSUE TITLE
Bruh

### ISSUE THREAD

**Issue by samuelrizzi-code** [luigi-budd/takis-the-fox#6]
There no way I can download this Takis addon/mod

**Comment by realslude** [comment]
In like what way? You can't download the zip? You can't turn the zip into a pk3 file? Can you be a bit more specific please

**Comment by samuelrizzi-code** [comment]
Ok what file

**Comment by luigi-budd** [comment]
No no, don't help him, Samuel Rizzi is smart enough to figure this out himself.

**Comment by samuelrizzi-code** [comment]
WeiT MIN

**Comment by samuelrizzi-code** [comment]
Did update your discord group?

**Comment by samuelrizzi-code** [comment]
How you know I'm sending messages

**Comment by samuelrizzi-code** [comment]
I saw the new image

**Comment by samuelrizzi-code** [comment]
I like it :)

**Comment by samuelrizzi-code** [comment]
Sedly I'm banned form the group I could get new update Takis :(

**Comment by samuelrizzi-code** [comment]
Soooooooo

**Comment by samuelrizzi-code** [comment]
🫤💀💀💀💀💀

**Comment by luigi-budd** [comment]
Hey how about you shut  up
