### ISSUE TITLE
Oops 

### ISSUE THREAD

**Issue by samuelrizzi-code** [luigi-budd/takis-the-fox#7]
I was trying to download src but idk how to do oh yeah well uhhhh idk

**Comment by luigi-budd** [comment]
Hey, you're smart, I know you can do it! Also not my issue, too bad!

**Comment by realslude** [comment]
And if you're not that smart or you're incapable to do it, just ask Joe! He's always helpful with these types of questions and he'll always be able to talk :)

**Comment by samuelrizzi-code** [comment]
Oh right I forgot tu realslude and actually I don't really mind about coding I'm not that smart is hard to make sprites and coding I only give ideas

**Comment by realslude** [comment]
I'm currently a bit confused... are you somehow talking about my Spongebob mod or the Takis mod as I don't work on the Takis mod, Luigi Budd and Joe work on it. But if you want to give suggestions to the Takis mod, join our [Discord server](https://discord.gg/r5MKneuGzF)!

**Comment by samuelrizzi-code** [comment]
Later

**Comment by samuelrizzi-code** [comment]
I'm busy right now
