### ISSUE TITLE
Takis gfz2 partial softlock

### ISSUE THREAD

**Issue by TailsTheAviationMaster** [luigi-budd/takis-the-fox#8]
This happened when playing gfz2 i had a lightning shield after images and i hit the red crawla combo by the springs and this happened
![srb2win 2023-10-27 16-43-10](https://github.com/luigi-budd/takis-the-fox/assets/141061172/716aa95f-c694-4e0a-9ef3-0b8551303be7)
Hopefully the image loaded

**Comment by TailsTheAviationMaster** [comment]
Strange, I can't to seem to replicate it, must've been partly from the mods I had.

**Comment by luigi-budd** [comment]
mustve been, some mods overriding the lives area
